### ISSUE TITLE
Error al hacer la inferencia:

### ISSUE THREAD

**Issue by Erikpr04** [ImPavloh/VoiceIt#1]
Buenas, he seguido paso a paso el readme, he agregado mi modelo pero cuando le doy a cambiar voz me sale este error: FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'd:\\prueba\\voiceit\\inference_output\\output.wav' -> 'output.wav'
Junto con más errores:
Traceback (most recent call last):
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "d:\cabron\voiceit\voiceit.py", line 129, in convert
    shutil.move(Path(INFERENCE_OUTPUT_DIRNAME, final_filename), Path(final_filename))
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
He verificado que estén instaladas las dependencias y parece que está todo correcto.
Soy bastante noob en todo esto pero creo que puede ser problema del shutil, puede que el error esté en la linea 129?? Estoy usando Python 3.8 .

**Comment by ImPavloh** [comment]
Hola, prueba a subir audios .wav y con un nombre sin símbolos ni espacios,
puede que el problema sea solo ese

**Comment by Corbi** [comment]
Tengo exactamente el mismo error. Estoy usando el nombre "audio1.wav".

**Comment by angelrb95** [comment]
Hola, tengo el mismo problema. El nombre del fichero es a.wav

**Comment by ImPavloh** [comment]
Cual es la duración del archivo y que modelo utilizais?

**Comment by angelrb95** [comment]
La duración es de unos 6 segundos y me pasa con todos los modelos

**Comment by JuanLagu** [comment]
Yo también tenía el mismo error y lo he conseguido hacer funcionar haciendo estos cambios en el fichero voiceit.py

- **Línea 24**: Reemplazar `filename = filename.split("/")[-1]` por `filename = filename.split("\\")[-1]`

- **Línea 43**: Reemplazar `f.write('file ' + str(seg.absolute()) + "\n")` por `f.write('file ' + str(seg.absolute()).replace("\\", "/") + "\n")`

- (Esta línea parece que no es necesaria, la dejo por si a alguien le sigue fallando) **Línea 44**: Reemplazar `os.system(f"ffmpeg -f concat -safe 0 -i {foldername}/concat_list.txt -codec copy {foldername}/{final_filename}")` por `os.system(f"ffmpeg -f concat -safe 0 -i {foldername}\concat_list.txt -codec copy {foldername}\{final_filename}")`

Dejo este mensaje por si les funciona a @Erikpr04 @Corbi @angelrb95

**Comment by ImPavloh** [comment]
Gracias por el mensaje @JuanLagu :)
Acabo de modificar el código y he cambiado otras cosas (por ejemplo, ahora se puede utilizar cualquier formato de audio ya que antes solo se podía `.wav`)

**Comment by JuanLagu** [comment]
He probado los cambios y funciona perfecto @ImPavloh
Muchas gracias por el curro 👏

**Comment by Anyeos** [comment]
amigo, habrá hecho algún cambio porque me tira este mismo error. Y el código:
`
os.system(f"ffmpeg -f concat -safe 0 -i {foldername}\\concat_list.txt -codec copy {foldername}\\{final_filename}")
`
Obviamente no funciona, directamente sale:
`
voiceit/inference_outputconcat_list.txt: No such file or directory
`

No sé por qué le puso la \\ si con solo ponerle / estaba bien. Lo cambié a / pero igual no anda:
`
voiceit/inference_output/concat_list.txt: Invalid data found when processing input
`

Me fijo el archivo y el mismo está vacío (0 bytes). 

Estoy tratando de deducir cómo genera ese archivo.

**Comment by ImPavloh** [comment]
Has actualizado todo desde que modifiqué el repositorio? He probado con distintos audios y todos los modelos SVC que hay en la web localmente y no he tenido ningún problema. Comprueba también que cumples los requisitos y tienes todo instalado

El problema deberia ya estar solucionado debido ha que he quitado la parte que daba el error y he cambiado mas cosas [*](https://github.com/ImPavloh/VoiceIt/issues/2#issuecomment-1613274605)
