### ISSUE TITLE
filename = filename.split("\\")[-1] no funciona para mi caso

### ISSUE THREAD

**Issue by Anyeos** [ImPavloh/VoiceIt#2]
Al final descubrí de dónde venía el problema. Tuve que cambiar:
`filename = filename.split("\\")[-1]`
por:
`filename = filename.split("/")[-1]`

O sea, claramente no hacía el split porque la ruta está con / no con \.
Si el script se va a ejecutar en Windows debería buscarse la forma más compatible de usar un delimitador de rutas. Sino definir algo como:
`PATH_DELIM="/"
if os.name == 'nt':
  PATH_DELIM="\\"
`
porque de lo contrario vamos a estar siempre teniendo problemas con el delimitador.

**Comment by ImPavloh** [comment]
Al final he decidido quitar la parte de dividir el audio ya que no es necesario localmente, además he aprovechado a cambiar alguna cosa, gracias igualmente, si sigues teniendo algún problema avisa :)
