### ISSUE TITLE
Misspelling: ‘module’ instead of ‘modulo Readme file

### ISSUE THREAD

**Issue by J-Saeedi** [ImPavloh/VoiceIt#3]
in English version of readme, `modelos` should be replaced with `models` or vise versa.

**Comment by ImPavloh** [comment]
Hey, thanks for pointing out the issue
I have addressed it by adding detection for both directories (`models `and `modelos`) in the latest commit [44de006]

**Comment by ImPavloh** [comment]
Hey, thanks for pointing out the issue
I have addressed it by adding detection for both directories (`models `and `modelos`) in the latest commit [44de006]
